'''
# created 06/10/2019 14:22
# by Q.Ducasse
'''

import cv2
import sklearn
import numpy             as np
import pandas            as pd
import seaborn           as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics         import confusion_matrix

# ============================================
#       CSV FILE LOADING AND VISUALISATION
# ============================================

## Paths creation and generation
## =============================

path_x_train = './data/x_train_gr_smpl.csv'
path_y_train = './data/y_train_smpl.csv'

## Data import & Preprocessing
## ===========================

# Import images vector values
signs = pd.read_csv(path_x_train, sep=',',na_values='None')
# Import labels
labels = pd.read_csv(path_y_train, sep=',',na_values='None')

# Link label to vectors
signs.insert(0,"label",labels.values)

# Line Randomisation
signs_rd = signs.sample(frac=1)
# Optional: Save again as CSV:
# signs_rd.to_csv('./data/x_train_gr_smpl_rd.csv')

# One label only data sets
# ========================

def create_one_label_dataset(nb):
    '''
    Return a dataset with only the labels nb
    '''
    label_is_correct = (signs['label'] == nb)
    signs_1label = signs[label_is_correct]
    path = './data/signs_label' + str(nb) + '.csv'
    signs_1label.to_csv(path)

def load_one_label_dataset(sample_nb):
    '''
    Load a dataset generated by create_one_label_dataset
    '''
    if ((sample_nb < 0) or (sample_nb > 9)):
        raise Exception('No data sample with that number')
    # Load the csv dataset
    dataframe = pd.read_csv('./data/signs_label' + str(sample_nb) + '.csv')
    # Drop the index column
    dataframe = dataframe.drop('Unnamed: 0', axis = 1)
    return dataframe

def dataset_with_boolean_mask(nb):
    '''
    Return the signs dataframe with labels formatted as:
        0 if label == nb
        1 if label != nb

        NOT WORKING !!!
    '''
    signs_1label = signs
    signs_1label.loc[signs_1label['label'] == nb, ['label']] = '0'
    signs_1label.loc[signs_1label['label'] != nb, ['label']] = '1'
    return signs_1label

def load_boolean_mask(nb):
    path_x_train = './data/x_train_gr_smpl.csv'
    path_labels  = './data/y_train_smpl_' + str(nb) + '.csv'
    signs_1label = pd.read_csv(path_x_train, sep=',',na_values='None')
    labels = pd.read_csv(path_labels, sep=',',na_values='None')
    signs_1label.insert(0,"label",labels.values)
    return signs_1label


## Data visualisation
## ==================
# Check the first and last rows of the basic + randomised data set
# print(signs.head(n=5))
# print(signs.tail(n=5))
# print(signs_rd.head(n=5))
# print(signs_rd.tail(n=5))
#print(signs['0'])

# Display the number of labels of each kind in the dataset
# plt.figure()
# sns.set(style="whitegrid", color_codes=True)
# sns.countplot('label',data=signs_rd)
# plt.show()


## Prepare training/test data
## ==========================

# Separation between feature vector (image itself) and target (label)
def separate_train_test(label_class, ratio=0.20):
    cols   = [col for col in signs_rd.columns if col!=label_class]
    data   = signs_rd[cols]
    target = signs_rd[label_class]

    # Separation between training/test data with the given ratio
    data_train, data_test, target_train, target_test = train_test_split(data,target, test_size = ratio, random_state = 10)
    return data_train, data_test, target_train, target_test

data_train, data_test, target_train, target_test = separate_train_test('label')

# ============================================
#            NAIVE BAYES BENCHMARK
# ============================================

# # import the necessary module
# from sklearn.naive_bayes import GaussianNB
# from sklearn.metrics     import accuracy_score
# #create an object of the type GaussianNB
# gnb = GaussianNB()
# #train the algorithm on training data and predict using the testing data
# pred = gnb.fit(data_train, target_train).predict(data_test)
# #print the accuracy score of the model
# print("Naive-Bayes accuracy : ", accuracy_score(target_test, pred, normalize = True))
#
# # create the confusion matrix of the model
# # with numpy
# bayes_conf_mat_np = confusion_matrix(target_test,pred)
# # with pandas
# bayes_conf_mat_pd = pd.crosstab(target_test,pred)
#
# # print(bayes_conf_mat_pd)

# ============================================
#           CORRELATION MATRIX
# ============================================

# Using Pearson Correlation

def store_best_abs_corr_attributes(nb):
    signs_1label = load_boolean_mask(nb)
    cor = signs_1label.corr()
    cor_target = abs(cor["label"])
    relevant_features = cor_target[cor_target>0.3].sort_values(ascending="False")
    relevant_features.to_csv('./data/best_features_smpl_' + str(nb) + '.csv')

store_best_abs_corr_attributes(3)

# Print heatmap
# plt.figure(figsize=(12,10))
# print(signs_label3['label'].corr(signs_label3['0']))
# sns.heatmap(cor, annot=True, cmap=plt.cm.Reds)
# plt.show()
